name: Deploy to CPanel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to CPanel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build frontend assets
      run: |
        npm install
        npm run build

    - name: Simulate `php artisan storage:link`
      run: |
          rm -rf public/storage
          mkdir -p public/storage
          cp -r storage/app/public/* public/storage/ || echo "No public storage content"

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./
          server-dir: public_html/
