name: Deploy via SSH to CPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to CPanel via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build frontend assets
      run: |
        npm install
        npm run build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy using rsync over SSH
      run: |
        rsync -az --delete \
        --exclude=".git*" \
        --exclude="node_modules" \
        --exclude="vendor" \
        ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER }}:/home/lxrapdcy/repositories/moen-electric/

   
    - name: Run Laravel commands on server
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.SERVER }} << 'EOF'
        cd /home/lxrapdcy/repositories/moen-electric
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan migrate --force
        php artisan storage:link
        EOF
